"""Generate js/questions.js and supabase/seed-questions.sql from questions.json.

One source of truth: questions.json. Run this after any edit to it.
"""
import json, os, io

HERE = os.path.dirname(os.path.abspath(__file__))
data = json.load(io.open(os.path.join(HERE, "questions.json"), encoding="utf-8"))

# --- check every question's sub-marks add up, and the paper adds to 150 ---
for paper in data["papers"]:
    total = 0
    subs = 0
    for q in paper["questions"]:
        s = sum(x["m"] for x in q["subs"])
        if s != q["marks"]:
            raise SystemExit("MISMATCH %s Q%s: subs=%d stated=%d" % (paper["code"], q["q"], s, q["marks"]))
        total += s
        subs += len(q["subs"])
    if total != paper["total"]:
        raise SystemExit("MISMATCH %s total=%d expected=%d" % (paper["code"], total, paper["total"]))
    print("%-12s %3d marks  %2d questions  %3d sub-questions  OK" % (
        paper["code"], total, len(paper["questions"]), subs))

# --- js ---
js = "// GENERATED by build.py from questions.json - do not hand-edit.\n"
js += "window.PAPERS = " + json.dumps(data["papers"], ensure_ascii=False, indent=2) + ";\n"
js += "window.TOPICS = " + json.dumps(data["topics"], ensure_ascii=False, indent=2) + ";\n"
with io.open(os.path.join(HERE, "js", "questions.js"), "w", encoding="utf-8", newline="\n") as f:
    f.write(js)

# --- sql seed ---
rows = []
for paper in data["papers"]:
    seq = 0
    for q in paper["questions"]:
        for s in q["subs"]:
            seq += 1
            rows.append((paper["code"], s["n"], q["q"], q["topic"], s["m"], seq,
                         s["en"], s["af"], q["head_en"], q["head_af"]))

def lit(v):
    if isinstance(v, int):
        return str(v)
    return "'" + v.replace("'", "''") + "'"

sql = ["-- GENERATED by build.py from questions.json - do not hand-edit.",
       "delete from public.exam_questions where paper_code in ('sept2024-p1','sept2024-p2');",
       "insert into public.exam_questions",
       "  (paper_code, qnum, q_main, topic, marks, seq, label_en, label_af, head_en, head_af)",
       "values"]
sql.append(",\n".join("  (" + ", ".join(lit(v) for v in r) + ")" for r in rows) + ";")
with io.open(os.path.join(HERE, "supabase", "seed-questions.sql"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(sql) + "\n")

print("wrote js/questions.js and supabase/seed-questions.sql (%d rows)" % len(rows))
